apiVersion: v1
kind: Service
metadata:
  labels:
    service: prediction
  name: prediction
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30007
  selector:
    service: prediction
  type: NodePort
status:
  loadBalancer: {}
